# DROP USER IF EXISTS 'user'@'%';

CREATE DATABASE IF NOT EXISTS `cms` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON cms.* TO 'user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
